version: '2'
services:
    application:
        build: ./application
        volumes:
          - ~/Workbench/www:/application

    docker-redis:
        build: ./redis
        ports:
          - "6379:6379"


    docker-mariadb:
        build: ./mariadb
        ports:
          - "3306:3306"
        volumes:
          - ./MariadbData:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=123456

    docker-php-fpm:
        build: ./php-fpm
        ports:
          - "9000:9000"
        volumes_from:
          - application
        links:
          - docker-mariadb:mysql
          - docker-redis:redis

    docker-nginx:
        build:
            context: ./nginx
            args:
              - PHP_UPSTREAM=fpm
            dockerfile: Dockerfile
        ports:
          - "80:80"
          - "443:443"
        volumes_from:
          - application
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/sites-enabled:/etc/nginx/sites-enabled
        links:
          - docker-php-fpm:fpm
